title: Hunter Ries
#description: Ph.D. student at UW–Madison studying viruses

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

social-network-links:
  email: "hries@wisc.edu"
  github: rieshunter
  linkedin: rieshunter
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
